# Generated by Django 4.2 on 2024-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='f1_score',
            field=models.TextField(default='[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='macro_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='num_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='precision',
            field=models.TextField(default='[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='recall',
            field=models.TextField(default='[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='support',
            field=models.TextField(default='[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='wieghted_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
