# Generated by Django 4.2 on 2024-06-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aimodel_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='confusion_matrix',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='f1_score',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='macro_avg',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='num_classes',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='precision',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='recall',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='support',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='wieghted_avg',
        ),
    ]
